package de.deutschebahn.ilv.businessobject;

/**
 * Created by AlbertLacambraBasil on 16.06.2017.
 */
public enum BOAction {
    CREATE_DEMAND,
    OPEN_DEMAND,
    CLOSE_DEMAND,
    SUBMIT_DEMAND,
    BLOCKED_DEMAND,
    APPROVE_DEMAND,
    REJECT_DEMAND,
    CORRECT_DEMAND,
    ACCEPT_DEMAND,
    REVOKE_DEMAND,
    COMPLETE_DEMAND,
    RESIGN_DEMAND,
    OFFER_IN_PROGRESS,
    NO_MORE_OPEN_OFFERS,
    MAKE_OFFER,

    OPEN_OFFER,
    SUBMIT_OFFER,
    ACCEPT_OFFER,
    REJECT_OFFER,
    APPROVE_OFFER,
    APPROVE_OFFER_INTERNAL,
    REVIEW_OFFER,
    CLOSE_OFFER,
    RESIGN_OFFER,
    REWORK_OFFER,
    COMPLETE_OFFER,
    REVOKE_OFFER,
    EXPIRE,
    ACTIVATE_OFFER,

    UPDATE,

    SIGN_CONTRACT,
    REJECT_CONTRACT,
    TERMINATE_CONTRACT,

    UPLOAD_DELIVERY,
    CREATE_DELIVERY_ENTRY,
    ADD_DELIVERY_PSP,
    CLOSE_DELIVERY
}
