package de.deutschebahn.ilv.businessobject;

public enum BOState {

    SUBMITTED,
    BLOCKED,
    OPENED,
    WAITING,
    APPROVED,
    OFFERED,
    ACCEPTED,
    EXPIRED,
    COMPLETED,
    CLOSED,
    LOCKED,

    NOT_CREATED,
    CREATED,
    CONTRACT_SUPPLIER_SIGNED,
    CONTRACT_CLIENT_SIGNED,
    CONTRACT_CREATED,
    CONTRACT_SIGNED,
    CONTRACT_TERMINATED,
    REJECTED,
    REVIEWED,
    TECH_APPROVED,
    COMM_APPROVED,

    DELIVERY_NOT_CREATED,
    DELIVERY_CREATED,
    DELIVERY_ACTIVE,
    DELIVERY_COMPLETE,
    DELIVERY_CLOSED
}
